package com.tradediary.ranking;
import com.tradediary.common.service.PnlCalculationService; import com.tradediary.position.*; import com.tradediary.user.*;
import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.math.*; import java.time.*; import java.time.format.DateTimeFormatter; import java.util.*; import java.util.stream.Collectors;
@Service @RequiredArgsConstructor public class RankingService {
 private static final int MIN_TRADES=5; private final PositionRepository positionRepository; private final UserRepository userRepository; private final PnlCalculationService pnlCalculationService;
 @Transactional(readOnly=true) public RankingResponse getRanking(Long myId,String requested){
  String category=Set.of("score","win_rate","return","risk").contains(requested)?requested:"score"; YearMonth month=YearMonth.now();
  Map<Long,List<Position>> grouped=positionRepository.findAllClosedInPeriod(month.atDay(1).atStartOfDay(),month.plusMonths(1).atDay(1).atStartOfDay()).stream().collect(Collectors.groupingBy(p->p.getUser().getId()));
  Map<Long,User> users=userRepository.findAllById(grouped.keySet()).stream().collect(Collectors.toMap(User::getId,u->u));
  List<Stats> ranked=grouped.entrySet().stream().filter(e->e.getValue().size()>=MIN_TRADES).filter(e->{User u=users.get(e.getKey());return u!=null&&Boolean.TRUE.equals(u.getProfilePublic())&&Boolean.TRUE.equals(u.getStatsPublic());}).map(e->calculate(e.getKey(),e.getValue(),users.get(e.getKey()))).sorted(comparator(category)).toList();
  List<RankingResponse.RankEntry> entries=new ArrayList<>(); for(int i=0;i<ranked.size();i++){Stats s=ranked.get(i);User u=users.get(s.userId);entries.add(new RankingResponse.RankEntry(i+1,s.userId,s.nickname,u.getAvatar(),s.tradeCount,s.winRate,money(s.pnl),nullableMoney(u.getTotalAssets()),s.returnPct,s.drawdownPct,s.consistencyPct,s.score,Objects.equals(s.userId,myId),Boolean.TRUE.equals(u.getDiaryPublic())));}
  Stats mine=grouped.containsKey(myId)?calculate(myId,grouped.get(myId),users.get(myId)):null; User me=users.get(myId);if(me==null)me=userRepository.findById(myId).orElse(null);Integer rank=null;for(int i=0;i<ranked.size();i++)if(Objects.equals(ranked.get(i).userId,myId)){rank=i+1;break;}
  RankingResponse.MyRank myRank=new RankingResponse.MyRank(rank,mine==null?0:mine.tradeCount,mine==null?0:mine.winRate,mine==null?"0.00":money(mine.pnl),me==null?null:nullableMoney(me.getTotalAssets()),mine==null?0:mine.returnPct,mine==null?0:mine.drawdownPct,mine==null?0:mine.consistencyPct,mine==null?0:mine.score,mine==null||mine.tradeCount<MIN_TRADES?"At least 5 closed trades are required this month.":null);
  return new RankingResponse(month.format(DateTimeFormatter.ofPattern("yyyy-MM")),category,entries,myRank);
 }
 private Stats calculate(Long id,List<Position> ps,User user){List<Position> sorted=ps.stream().sorted(Comparator.comparing(Position::getClosedAt)).toList();int wins=(int)sorted.stream().filter(p->p.getPnl().signum()>0).count();BigDecimal pnl=pnlCalculationService.sumKrw(sorted),capital=BigDecimal.ZERO,running=BigDecimal.ZERO,peak=BigDecimal.ZERO,dd=BigDecimal.ZERO;Map<LocalDate,BigDecimal> days=new HashMap<>();for(Position p:sorted){BigDecimal v=pnlCalculationService.toKrw(p);running=running.add(v);peak=peak.max(running);dd=dd.max(peak.subtract(running));capital=capital.add(pnlCalculationService.amountToKrw(p,p.getEntryPrice().multiply(p.getQty()).abs()));days.merge(p.getClosedAt().toLocalDate(),v,BigDecimal::add);}double wr=round(wins*100.0/sorted.size()),ret=percent(pnl,capital),draw=percent(dd,capital),consistency=round(days.values().stream().filter(v->v.signum()>0).count()*100.0/Math.max(1,days.size())),sample=Math.min(1,sorted.size()/20.0);double score=round(clamp(wr/100)*30+clamp((ret+10)/30)*25+(1-clamp(draw/20))*25+clamp(consistency/100)*10+sample*10);return new Stats(id,user==null?"Trader":user.getNickname(),sorted.size(),wr,pnl,ret,draw,consistency,score);}
 private Comparator<Stats> comparator(String c){Comparator<Stats>x=switch(c){case"win_rate"->Comparator.comparingDouble(Stats::winRate);case"return"->Comparator.comparingDouble(Stats::returnPct);case"risk"->Comparator.comparingDouble(Stats::drawdownPct).reversed();default->Comparator.comparingDouble(Stats::score);};return x.reversed().thenComparing(Comparator.comparingDouble(Stats::score).reversed());}
 private double percent(BigDecimal a,BigDecimal b){return b.signum()==0?0:round(a.divide(b,8,RoundingMode.HALF_UP).doubleValue()*100);}private double clamp(double n){return Math.max(0,Math.min(1,n));}private double round(double n){return Math.round(n*100.0)/100.0;}private String money(BigDecimal n){return n.setScale(2,RoundingMode.HALF_UP).toPlainString();}private String nullableMoney(BigDecimal n){return n==null?null:money(n);}private record Stats(Long userId,String nickname,int tradeCount,double winRate,BigDecimal pnl,double returnPct,double drawdownPct,double consistencyPct,double score){}
}
