export const translations = {
  'Start free':'무료로 시작하기','A clearer way to improve your trading':'더 명확하게 성장하는 트레이딩 방법','Your trades.':'당신의 거래.','Your edge.':'당신만의 경쟁력.','Sync your trades, review every decision and understand what actually drives your performance.':'거래를 동기화하고 모든 결정을 복기하여 무엇이 실제 성과를 만드는지 확인하세요.','Write today’s journal':'오늘의 일지 작성','View trade history':'거래 기록 보기','Supported exchanges':'지원 거래소','How it works':'이용 방법','From execution to insight':'체결부터 인사이트까지','Core features':'핵심 기능','Everything you need to review your edge':'트레이딩 경쟁력을 복기하는 데 필요한 모든 기능','Connect':'연결','Review':'복기','Improve':'개선','Automatic trade sync':'자동 거래 동기화','Portfolio analytics':'포트폴리오 분석','Trading journal':'매매 일지','AI performance review':'AI 성과 분석','Review today’s decisions':'오늘의 결정을 복기하세요','Build a better trading process':'더 나은 트레이딩 과정을 만드세요',
  'Welcome back':'다시 오신 것을 환영합니다','Trading overview':'트레이딩 개요','Loading your workspace...':'작업 공간을 불러오는 중...','Positions this month':'이번 달 포지션','Monthly win rate':'이번 달 승률','Monthly PnL':'이번 달 손익','Insights':'인사이트','Recent positions':'최근 포지션','View all →':'전체 보기 →','Set up your trading workspace':'트레이딩 작업 공간 설정','Connect exchange':'거래소 연결','Sync history':'거래 기록 동기화','Review performance':'성과 분석','Quick access':'빠른 메뉴','Monthly goal':'이번 달 목표','Target win rate (%)':'목표 승률 (%)','Target profit (USDT)':'목표 수익 (USDT)','Target trade count':'목표 거래 수','Trade count':'거래 수','Goal complete':'목표 달성','Edit goal':'목표 수정','+ Add goal':'+ 목표 추가','Save goal':'목표 저장','Saving...':'저장 중...','Deleting...':'삭제 중...','Set a monthly goal to track your progress at a glance.':'이번 달 목표를 설정하고 달성 현황을 한눈에 확인하세요.','Trade plans':'매매 계획',
  'QUICK PROFILE':'빠른 프로필','Personal workspace':'개인 작업 공간','Saved':'저장됨','Could not save':'저장하지 못했습니다','Use light':'라이트 모드','Use dark':'다크 모드','Account details':'계정 정보','Exchange connections':'거래소 연결','Advanced settings':'고급 설정','Current theme: dark':'현재 테마: 다크','Current theme: light':'현재 테마: 라이트','ACCOUNT':'계정','Open navigation':'메뉴 열기',
  'Home':'홈','Overview':'개요','Portfolio':'포트폴리오','Positions':'포지션','Executions':'체결 내역','Holdings':'보유 자산','Analytics':'분석','Performance':'성과','Journal':'매매 일지','Trade Plans':'매매 계획','Community':'커뮤니티','Ranking':'랭킹','Settings':'설정','Connections':'거래소 연결','Notifications':'알림','Profile':'프로필','Security':'보안','Appearance':'화면 설정','Language':'언어','Sign out':'로그아웃','Sign in':'로그인','Create account':'회원가입',
  'New journal':'새 일지','New entry':'새 기록','Add connection':'거래소 연결','Live sync':'실시간 동기화','Sync now':'지금 동기화','Reconnect':'다시 연결','Delete':'삭제','Edit':'수정','Save':'저장','Cancel':'취소','Close':'닫기','Retry':'다시 시도','Search':'검색','All':'전체','Following':'팔로잉','Discussions':'게시판','Following only':'팔로잉만','Loading...':'불러오는 중...','Up to date':'최신 상태',
  'Exchange Connections':'거래소 연결','Manage read-only API connections':'읽기 전용 거래소 API 연결을 관리합니다','Connected exchanges':'연결된 거래소','Display name':'표시 이름','Update password':'비밀번호 변경','Current password':'현재 비밀번호','New password':'새 비밀번호','Confirm password':'비밀번호 확인','English':'영어','Korean':'한국어','Theme':'테마','Light':'라이트','Dark':'다크','System':'시스템',
  'Monthly Ranking':'월간 랭킹','Overall':'종합','Return':'수익률','Win rate':'승률','Low risk':'낮은 위험','Trades':'거래 수','Assets':'자산','Profit':'수익','Risk level':'위험 수준','Maximum drawdown':'최대 낙폭','Current assets':'현재 자산','Period PnL':'기간 손익','This month':'이번 달','Trading style':'매매 스타일','Behavioral summary':'거래 행동 요약','Average holding time':'평균 보유 시간','Capital-weighted return':'투입 자본 수익률','Best streak':'최대 연승','Cumulative performance':'누적 성과','Recent closed positions':'최근 청산 포지션','Market':'마켓','Side':'방향','Closed':'청산일','Realized PnL':'실현 손익',
  'Following activity':'팔로잉 활동','Public journals and verified closed positions only':'공개 일지와 검증된 청산 포지션만 표시됩니다','Your following feed is quiet':'팔로잉 피드가 아직 비어 있습니다','No data yet':'아직 데이터가 없습니다','No performance data yet':'아직 성과 데이터가 없습니다','No trading activity in this period':'이 기간에는 거래 활동이 없습니다','No closed positions in this period':'이 기간에는 청산 포지션이 없습니다','Loading data':'데이터를 불러오는 중','Loading portfolio':'포트폴리오를 불러오는 중','Unable to load data':'데이터를 불러올 수 없습니다','View all history':'전체 기록 보기',
  'Trading Journal':'매매 일지','Trading emotion':'매매 감정','Entry reason':'진입 이유','Exit reason':'청산 이유','Strategy tags':'전략 태그','Notes':'메모','Review checklist':'복기 체크리스트','Before entry':'진입 전','Before exit':'청산 전','Visibility':'공개 범위','Private':'비공개','Public':'공개','Only you can see this':'나만 볼 수 있습니다','Shown on your public profile':'공개 프로필에 표시됩니다','Photo attachment':'사진 첨부','Choose photo':'사진 선택','New tag':'새 태그','Add':'추가',
  'Dashboard':'대시보드','Total assets':'총 자산','Add goal':'목표 추가','Today’s market brief':'오늘의 시장 요약',"Today's market brief":'오늘의 시장 요약','Generate summary':'요약 생성','No summary is available for today. Select ↺ to generate one.':'오늘의 요약이 없습니다. ↺ 버튼을 눌러 생성하세요.','AI is preparing the summary...':'AI가 요약을 생성하고 있습니다...',
  'Symbol':'종목','Direction':'방향','Quantity':'수량','Entry price':'진입가','Exit price':'청산가','PnL':'손익','PnL rate':'수익률','Closed at':'청산 일시','Long':'롱','Short':'숏','Complete':'완료','Incomplete':'미완료','Planned':'계획됨','Completed':'완료됨','No results':'결과가 없습니다','No positions yet':'아직 포지션이 없습니다','No holdings yet':'아직 보유 자산이 없습니다','No executions yet':'아직 체결 내역이 없습니다'
};

Object.assign(translations, {
  '+ Insert image at cursor':'+ 커서 위치에 이미지 삽입','01 · Explain your thesis':'01 · 근거를 설명하세요','02 · State the risk':'02 · 위험을 명시하세요','03 · Respect other traders':'03 · 다른 트레이더를 존중하세요','1 minute':'1분','30 seconds':'30초','5 minutes':'5분','1. Connect exchange':'1. 거래소 연결','2. Sync executions':'2. 체결 내역 동기화','3. Review positions':'3. 포지션 검토','COMMUNITY DESK':'커뮤니티 데스크','Complete the steps below to display positions.':'아래 단계를 완료하면 포지션이 표시됩니다.','Connect an exchange to unlock position tracking, performance analytics and trading insights.':'거래소를 연결하여 포지션 추적, 성과 분석과 트레이딩 인사이트를 이용하세요.','Exchange':'거래소','Exchange API Key Add':'거래소 API 키 추가','Journal Delete':'일지 삭제','Loading…':'불러오는 중…','Loss':'손실','PNG, JPEG or WebP · 1.5 MB max':'PNG, JPEG 또는 WebP · 최대 1.5MB','Rank':'순위','Starting capital':'시작 자본','Trade Diary':'트레이드 다이어리','Trade Sync':'거래 동기화','Trading return uses realized PnL divided by deployed entry capital. Deposits, withdrawals and time-weighted return will remain unavailable until balance history collection is enabled.':'거래 수익률은 실현 손익을 투입 진입 자본으로 나누어 계산합니다. 잔액 이력 수집 전에는 입금, 출금과 시간가중 수익률을 제공하지 않습니다.','Type':'유형','View board':'게시판 보기','← Back':'← 뒤로','← Back to board':'← 게시판으로 돌아가기','● Today':'● 오늘',
  '24시간 고가':'24시간 최고가','24시간 저가':'24시간 최저가','Add된 Exchange 없음':'연결된 거래소가 없습니다','data 상태':'데이터 상태','Entry 이유':'진입 이유','Exit 이유':'청산 이유','Exchange connection 후 data를 불러오고 있습니다. 잠시만 기다려주세요.':'거래소 연결 후 데이터를 불러오고 있습니다. 잠시만 기다려주세요.','Exchange connection하기':'거래소 연결하기','Holdings 없음':'보유 자산이 없습니다','Sync 버튼 클릭':'동기화 버튼 클릭','Trade 없음':'거래가 없습니다','당일 Trade history':'당일 거래 내역','선택한 기간에 Trade history이 없습니다':'선택한 기간에 거래 내역이 없습니다','위 Sync 버튼을 or it will sync automatically every five minutes.':'위 동기화 버튼을 누르거나 5분 간격 자동 동기화를 기다리세요.','이 Journal를 Delete하시겠습니까? 되돌릴 수 없습니다.':'이 일지를 삭제하시겠습니까? 삭제 후 되돌릴 수 없습니다.','이 날 Trade history이 없습니다':'이 날짜에는 거래 내역이 없습니다','조회중...':'불러오는 중...','평가 금액':'평가 금액','현재가':'현재가','현재가를 조회하고 있습니다...':'현재가를 불러오는 중...','🤖 AI 피드백':'🤖 AI 피드백','닫기':'닫기','메모':'메모','시각':'시각','체크리스트':'체크리스트',
  'Connection unavailable':'연결 확인 필요','Add API key':'API 키 추가','Last sync: 5 minutes ago':'마지막 동기화: 5분 전','Sync detects new executions and updates positions automatically.':'새 체결을 감지하여 포지션을 자동으로 갱신합니다.','A: Run it manually after new executions, or wait for the automatic five-minute sync.':'A: 새 체결 후 직접 실행하거나 5분 간격 자동 동기화를 기다리세요.','A: Existing history is preserved and only newly detected executions are added.':'A: 기존 기록은 유지되며 새로 감지된 체결만 추가됩니다.','Q: What if the data looks incorrect?':'Q: 데이터가 잘못 표시되면 어떻게 하나요?','A: Run sync again to rebuild all calculated positions.':'A: 동기화를 다시 실행하여 계산된 포지션을 재구성하세요.',
  'Password updated':'비밀번호 변경 완료','Sign in with your new password.':'새 비밀번호로 로그인하세요.','Go to sign in':'로그인으로 이동','Set a new password':'새 비밀번호 설정','Use at least 8 characters including one uppercase letter.':'대문자 하나를 포함하여 8자 이상 입력하세요.','This link is invalid. Open the password reset link from your email again.':'유효하지 않은 링크입니다. 이메일에서 비밀번호 재설정 링크를 다시 열어주세요.','8+ characters':'8자 이상','One uppercase letter':'대문자 하나','Passwords match':'비밀번호 일치','Updating...':'변경 중...','Change password':'비밀번호 변경','Back home':'홈으로 돌아가기','Trader profile':'트레이더 프로필',
  'Incorrect email or password.':'이메일 또는 비밀번호가 올바르지 않습니다.','We could not create your account.':'계정을 만들 수 없습니다.','Registration failed.':'등록에 실패했습니다.','This link is expired or invalid.':'만료되었거나 유효하지 않은 링크입니다.','Could not update the follow status.':'팔로우 상태를 변경할 수 없습니다.','Your session needs to be refreshed. Please try again.':'세션을 갱신해야 합니다. 다시 시도해주세요.','Sign in is required.':'로그인이 필요합니다.','Could not generate the summary.':'요약을 생성하지 못했습니다.','An internal server error occurred.':'서버 내부 오류가 발생했습니다.',
  'Could not save the language preference.':'언어 설정을 저장하지 못했습니다.','Language preference saved.':'언어 설정이 저장되었습니다.',
  'Back to ranking':'랭킹으로 돌아가기','Back to board':'게시판으로 돌아가기','Today':'오늘','Calendar':'캘린더','Start date':'시작일','End date':'종료일','Clear':'초기화','Refresh':'새로고침','Comment':'댓글','New discussion':'새 게시글','New post':'새 게시물','Publish post':'게시하기','Post preview':'게시물 미리보기','Indicative preview':'예상 화면','Latest discussions':'최신 게시글','Ideas, reviews and market notes from the community.':'커뮤니티의 시장 아이디어와 매매 복기를 확인하세요.','Start the first discussion.':'첫 번째 게시글을 작성해 보세요.','The board is ready for your market idea.':'시장 아이디어를 공유할 게시판이 준비되었습니다.','Write a clear title and add useful context.':'명확한 제목과 도움이 되는 배경 정보를 작성하세요.','Posting standards':'게시 기준','Respect other traders':'다른 트레이더를 존중하세요','Share the setup, the risk and what would invalidate your idea. Specific context creates useful discussion.':'진입 근거와 위험, 아이디어가 무효화되는 조건을 공유하세요. 구체적인 맥락이 유용한 토론을 만듭니다.','replies':'댓글','views':'조회','recent topics':'최근 주제',
  'Create your trading workspace':'트레이딩 작업 공간 만들기','Sign in to your trading workspace':'트레이딩 작업 공간에 로그인','Email':'이메일','Password':'비밀번호','Remember email':'이메일 기억','or':'또는','Completing sign-in...':'로그인을 완료하는 중...','Profile photo':'프로필 사진','Save profile':'프로필 저장','Update the identity shown across your workspace.':'작업 공간에 표시되는 프로필 정보를 변경합니다.','Change the password used for email sign-in.':'이메일 로그인에 사용하는 비밀번호를 변경합니다.','Choose how the workspace is displayed.':'작업 공간의 표시 방식을 선택합니다.','Control what other signed-in traders can view.':'다른 로그인 사용자가 볼 수 있는 정보를 설정합니다.','Notification settings':'알림 설정','Public profile':'공개 프로필','Public data':'공개 데이터','Data scope':'데이터 공개 범위',
  'Choose an exchange to connect':'연결할 거래소를 선택하세요','Enter your read-only API credentials':'읽기 전용 API 인증 정보를 입력하세요','API Key':'API 키','Secret Key':'시크릿 키','Passphrase':'패스프레이즈','IP allowlist':'IP 허용 목록','IP allowlist required':'IP 허용 목록 설정 필수','This exchange is already connected. Saving will replace the existing credentials.':'이미 연결된 거래소입니다. 저장하면 기존 인증 정보가 교체됩니다.','No connected exchanges':'연결된 거래소가 없습니다','Add an exchange API key to begin.':'거래소 API 키를 추가하여 시작하세요.','Use the button below to connect an exchange.':'아래 버튼을 눌러 거래소를 연결하세요.','Connected':'연결됨','Sync executions':'체결 내역 동기화','Sync execution history from each exchange and rebuild positions automatically.':'각 거래소의 체결 기록을 동기화하고 포지션을 자동으로 재구성합니다.','Sync in progress':'동기화 중','Loading balances...':'잔액을 불러오는 중...','Loading activity...':'활동 내역을 불러오는 중...','Available Balance':'사용 가능 잔액','Available to close':'청산 가능 수량','All Balance':'전체 잔액','All Exchange':'전체 거래소','All Journal':'전체 일지','Select Exchange':'거래소 선택','Frequently asked questions':'자주 묻는 질문','Q: How often should I sync?':'Q: 얼마나 자주 동기화해야 하나요?','Q: What happens to existing trade history?':'Q: 기존 거래 기록은 어떻게 되나요?',
  'PERFORMANCE OVERVIEW':'성과 개요','Key performance metrics':'핵심 성과 지표','Total positions':'전체 포지션','Total PnL':'전체 손익','Average PnL':'평균 손익','Wins / Losses':'승리 / 패배','Longest win streak':'최대 연승','Longest loss streak':'최대 연패','Daily PnL':'일별 손익','Cumulative PnL':'누적 손익','Performance curve':'성과 곡선','Performance preview':'성과 미리보기','Performance by symbol':'종목별 성과','Performance by weekday':'요일별 성과','Performance by hour (exit time)':'시간대별 성과(청산 시간)','PnL calendar':'손익 캘린더','Long / Short comparison':'롱 / 숏 비교','Win rate by emotion':'감정별 승률','Symbol performance':'종목별 성과','Win rate, sample size and realized result by market':'마켓별 승률, 표본 수 및 실현 손익','Change the date range or select All time.':'기간을 변경하거나 전체 기간을 선택하세요.','No performance data to display.':'표시할 성과 데이터가 없습니다.','No performance data.':'성과 데이터가 없습니다.','Connect and sync trading data to unlock analytics.':'거래소를 연결하고 거래 데이터를 동기화하면 분석을 확인할 수 있습니다.','Once closed positions are available, this page calculates win rate, risk-to-reward, PnL trends and calendar insights.':'청산 포지션이 생기면 승률, 손익비, 손익 추세와 캘린더 인사이트를 계산합니다.','Calculating performance...':'성과를 계산하는 중...','Analyzing current performance...':'현재 성과를 분석하는 중...',
  'Trade history':'거래 내역','Verified executions':'검증된 체결 내역','No execution history.':'체결 내역이 없습니다.','No position history.':'포지션 내역이 없습니다.','No executions for this day':'이 날짜에는 체결 내역이 없습니다','Executions for this day':'이 날짜의 체결 내역','No trades':'거래가 없습니다','Entry':'진입','Exit':'청산','Entry rationale':'진입 근거','Exit rationale':'청산 근거','Entry recorded':'진입 기록됨','Executed at':'체결 시간','Time':'시간','Price':'가격','Fee':'수수료','Leverage':'레버리지','Mark price':'시장가','Average entry':'평균 진입가','Unrealized PnL':'미실현 손익','Asset':'자산','ASSET DETAIL':'자산 상세','Indicative':'예상값','Side not set':'방향 미설정','30-day trade pace':'30일 거래 빈도','Latest verified results in the selected period':'선택 기간의 최신 검증 결과','Calculated from publicly shared closed positions.':'공개된 청산 포지션을 기준으로 계산됩니다.','VERIFIED PORTFOLIO':'검증된 포트폴리오','Return methodology':'수익률 계산 방식','Private performance':'비공개 성과','PUBLIC TRADER PROFILE':'공개 트레이더 프로필','No trader profile yet':'아직 트레이더 유형이 없습니다','A profile is calculated only from your current performance data. Complete at least five closed positions to unlock it. Any older cached profile has been removed.':'트레이더 유형은 현재 성과 데이터만으로 계산됩니다. 청산 포지션 5개 이상이 쌓이면 확인할 수 있으며 이전 캐시 결과는 제거됩니다.','DATA REQUIRED':'데이터 필요','BEHAVIOR PROFILE':'행동 프로필','AI coaching':'AI 코칭','Monthly review':'월간 복기','Weekly review':'주간 복기','AI challenge':'AI 챌린지','Strength:':'강점:','Watch:':'주의:',
  'Better decisions start with better notes.':'더 나은 기록이 더 나은 결정을 만듭니다.','Document your decision before entering and review execution later in the journal.':'진입 전에 계획을 기록하고 체결 후 일지에서 복기하세요.','Write a pre-trade plan and track whether you followed it.':'매매 전 계획을 작성하고 실행 여부를 확인하세요.','New plan':'새 계획','Create first plan':'첫 계획 만들기','Entries this month':'이번 달 기록','Entry price (₩)':'진입가 (₩)','Exit price (₩)':'청산가 (₩)','Price (₩)':'가격 (₩)','Fee (₩)':'수수료 (₩)','PnL (₩)':'손익 (₩)','No public journal entries.':'공개 일지가 없습니다.','All time':'전체 기간','Mark all read':'모두 읽음','No new activity':'새 알림이 없습니다','Updates from trades, reports and connections will appear here.':'거래, 리포트와 연결 관련 알림이 여기에 표시됩니다.','Live updates connected':'실시간 업데이트 연결됨','Market News':'시장 뉴스','Live English coverage from CryptoCompare':'CryptoCompare의 실시간 영문 뉴스','No news is available.':'현재 뉴스가 없습니다.','Searching...':'검색 중...','Loading discussions...':'게시글을 불러오는 중...','Loading plans...':'계획을 불러오는 중...','Off':'꺼짐','NOW':'현재','ACTIVITY':'활동','LIVE':'실시간'
});

const englishByKorean = Object.entries(translations).reduce((result, [english, korean]) => {
  if (!(korean in result)) result[korean] = english;
  return result;
}, {
  '요약 생성에 실패했습니다.':'Could not generate the summary.',
  '서버 내부 오류가 발생했습니다.':'An internal server error occurred.',
  '로그인이 필요합니다.':'Sign in is required.',
  '거래소 연결':'Exchange connection','거래소':'Exchange','종목':'Symbol','수량':'Quantity','진입가':'Entry price','청산가':'Exit price','청산일시':'Closed at','수익률':'Return','손익':'PnL',
  '언어 설정이 저장되었습니다.':'Language preference saved.','설정':'Settings','공개':'Public','비공개':'Private','사진 첨부':'Photo attachment','사진 선택':'Choose photo'
  ,'24시간 고가':'24-hour high','24시간 저가':'24-hour low','Add된 Exchange 없음':'No connected exchanges','Exchange connection 후 data를 불러오고 있습니다. 잠시만 기다려주세요.':'Loading exchange data. Please wait.','Exchange connection하기':'Connect exchange','All Balance':'All balances','All Exchange':'All exchanges','All Journal':'All journals','Holdings 없음':'No holdings','Trade 없음':'No trades','data 상태':'Data status','Entry 이유':'Entry rationale','Exit 이유':'Exit rationale','현재가':'Current price','현재가를 조회하고 있습니다...':'Loading current price...','평가 금액':'Estimated value','시각':'Time','당일 Trade history':'Trades for this day','이 날 Trade history이 없습니다':'No trades for this day','선택한 기간에 Trade history이 없습니다':'No trades in the selected period','조회중...':'Loading...','체크리스트':'Checklist','메모':'Notes','닫기':'Close','🤖 AI 피드백':'🤖 AI feedback','AI 챌린지를 준비 중...':'Preparing the AI challenge...','이 Journal를 Delete하시겠습니까? 되돌릴 수 없습니다.':'Delete this journal? This cannot be undone.','Sync 버튼 클릭':'Select Sync','위 Sync 버튼을 or it will sync automatically every five minutes.':'Select Sync above or wait for the automatic five-minute sync.'
});

export const translateText = (value, language) => {
  if (!value) return value;
  if (language !== 'ko') return englishByKorean[value] || value;
  const exact = translations[value]; if (exact) return exact;
  const patterns = [
    [/^(\d+) trades$/, '$1회 거래'], [/^(\d+) closed positions$/, '$1개 청산 포지션'],
    [/^Last activity was (.+)\. Try a wider range\.$/, '마지막 거래는 $1입니다. 더 넓은 기간을 선택하세요.'],
    [/^Published a journal(?: · (.+))?$/, (_, symbol) => `공개 일지를 작성했습니다${symbol ? ` · ${symbol}` : ''}`],
    [/^(LONG|SHORT) (.+) closed · ([+-]?[\d.]+)%$/, (_, side, symbol, rate) => `${side === 'LONG' ? '롱' : '숏'} ${symbol} 청산 · ${rate}%`]
  ];
  for (const [regex, replacement] of patterns) if (regex.test(value)) return value.replace(regex, replacement);
  return value;
};
